export const WEATHER_DATA_LOADING = 'WEATHER_DATA_LOADING';
export const WEATHER_DATA_LOADING_SUCCESS = 'WEATHER_DATA_LOADING_SUCCESS';
export const WEATHER_DATA_LOADING_FAIL = 'WEATHER_DATA_LOADING_FAIL';

export const RESTAURANTS_DATA_LOADING = 'RESTAURANTS_DATA_LOADING';
export const RESTAURANTS_DATA_LOADING_SUCCESS = 'RESTAURANTS_DATA_LOADING_SUCCESS';
export const RESTAURANTS_DATA_LOADING_FAIL = 'RESTAURANTS_DATA_LOADING_FAIL';